Iter13
Svirex/microurl pull request #13
Opened 2024-03-18 07:09 UTC by Svirex

2024-03-19 19:50 UTC, popoffvg commented on internal/storage/postgres.go
> +CREATE TABLE IF NOT EXISTS
Схему стоит изменять с помощью библиотек для миграции:
- golang-migrate
- goose

2024-03-19 19:50 UTC, popoffvg commented on internal/storage/postgres.go
> +	if err == sql.ErrNoRows {
Ошибки всегда стоит проверять через errors.Is, т.к. реализацию драйвера могут подменить / обернуть и на равно ошибка проверяться пересатнет.

2024-03-19 19:50 UTC, popoffvg commented on internal/storage/postgres.go
> +			return nil, fmt.Errorf("%w", err)
Так оборачивать ошибку не стоит. нужно обязательно добавлять текст, по которому можно будет понять место возникновение ошибки. Чем уникальнее он будет, тем лучше.

2024-03-24 15:59 UTC, popoffvg requested changes

2024-03-24 15:59 UTC, popoffvg commented on cmd/client/main.go
> +func main() {
Лучше было сделать такой тест

2024-03-24 15:59 UTC, popoffvg commented on cmd/client/main.go
> +	req, _ := http.NewRequest(http.MethodPost, "http://localhost:8080/api/shorten/batch", bytes.NewReader(bodyBytes))
Тут необязательно, но в реальном приложении всегда стоит использовать `NewRequestWithContext`.

2024-03-24 15:59 UTC, popoffvg commented on cmd/shortener/main.go
> +	var db *sqlx.DB
В реальных проектах при большом кол-ве компонент main превратиться в лапшу очень быстро. Нужно стараться выделять конструкторы. 
В данном случае в main должно было остаться только
```
repository, err := newRepository(/*...*/)
```

2024-03-24 15:59 UTC, popoffvg commented on internal/apis/shortener.go
> +		w.WriteHeader(http.StatusConflict)
лучше стараться не писать цепочки if-else. При более сложном коде они быстро превращаются в лапшу. В первом if и последнем почему-то пропущен return. если `serviceReulst == nil`, то будет паника.

2024-03-24 15:59 UTC, popoffvg commented on internal/apis/shortener.go
> +	r.Body.Close()
Тело следует закрывать после проверки на ошибку

2024-03-24 15:59 UTC, popoffvg commented on internal/apis/shortener.go
> +			serviceResult.Records[i].ShortURL = fmt.Sprintf("%s/%s", api.BaseURL, serviceResult.Records[i].ShortURL)
Эта логика сервиса, должна быть внутри сервисного слоя.

2024-03-24 15:59 UTC, popoffvg commented on internal/logging/zap_logger.go
> +		return nil, err
Ошибку нужно обернуть

2024-03-24 15:59 UTC, popoffvg commented on internal/services/shortener.go
> +		return nil, ErrNotFound
Оборачивай ошибку. В реальном проекте никогда не узнать, что пошло не так при таком подходе. 
```go
fmt.Errorf("%w: get by short id: %w", ErrNotFound, err)
```

2024-03-24 15:59 UTC, popoffvg commented on internal/storage/postgres.go
> +		return nil, ErrSomtheingWrong
Тут стоит оборачивать, а не зменять sentinel ошибкой.

2024-03-27 05:25 UTC, Svirex commented on internal/apis/shortener.go
> +			serviceResult.Records[i].ShortURL = fmt.Sprintf("%s/%s", api.BaseURL, serviceResult.Records[i].ShortURL)
Здесь по идее ещё адаптер нужен. 
У сервиса нет задачи выдать в каком-то виде ссылку. Он выдаёт сокращенный ID. А в каком виде передавать пользователю - в виде ссылки или в виде строки - сервис не должен знать ничего об этом.

2024-05-15 06:00 UTC, merged