Iter5
Svirex/microurl pull request #5
Opened 2024-02-08 10:34 UTC by Svirex

2024-02-10 08:08 UTC, popoffvg requested changes

2024-02-10 08:08 UTC, popoffvg commented on cmd/shortener/flags.go
> +	if baseURL != "" {
Лучше для таких операций использовать пакет url

2024-02-10 08:08 UTC, popoffvg commented on internal/generators/simple.go
> +var _ util.Generator = &SimpleGenerator{}
такую проверку обычно пишут чуть по-другому:
`var r _ util.Generator = (*SimpleGenerator)(nil)`

2024-02-10 08:08 UTC, popoffvg commented on internal/generators/simple.go
> +func (g *SimpleGenerator) RandString(size int) string {
Лучше использовать uint

2024-02-10 08:08 UTC, popoffvg commented on internal/handlers/root.go
> +		url, err := io.ReadAll(r.Body)
Тело нужно обязательно закрывать

2024-02-10 08:08 UTC, popoffvg commented on internal/handlers/root.go
> +			w.WriteHeader(http.StatusBadRequest)
А как узнать какая ошибка произошла?

2024-02-10 08:08 UTC, popoffvg commented on internal/pkg/context/context.go
> +package context
Лучше не называть пакет context, т.к. также называется пакет стандартной библиотеки, который очень часто используется.

2024-02-10 08:08 UTC, popoffvg commented on internal/pkg/server/server.go
> +	router := chi.NewRouter()
Всегда нужно добавлять рековери мидлвару, т.к. при панике в хендлерах без мидлвары клиент увидит не 500, а разрыв соединения

2024-02-10 08:08 UTC, popoffvg commented on internal/pkg/server/server.go
> +	if err != nil {
Всегда нужно проверять на ошибку ErrServerClose, которая возвращается при успешном завершении работы сервера

2024-02-10 08:08 UTC, popoffvg commented on internal/storage/inmemory.go
> +	m.data[shortID] = url
Мапа не конкурентно безопасно и при параллельной записи будет паника. Нужно защищать мьютексами

2024-02-10 08:08 UTC, popoffvg commented on internal/pkg/repositories/repository.go
> +	Add(shortID, url string) error
Текущий интерфейс не позволяет легко расширять модель данных. Например, как добавить владельца ссылки?

2024-02-13 06:34 UTC, Svirex commented on cmd/shortener/flags.go
> +	if baseURL != "" {
url.Parse адрес вида localhost:8080 парсит неправильно. Он распознаёт localhost как URL.Scheme.

2024-02-13 06:55 UTC, Svirex commented on internal/handlers/root.go
> +			w.WriteHeader(http.StatusBadRequest)
В условие к Инкременту 1 сказано, что "На любой некорректный запрос сервер должен возвращать ответ с кодом 400."

2024-02-14 20:22 UTC, popoffvg approved these changes

2024-02-14 20:22 UTC, popoffvg commented on cmd/shortener/flags.go
> +	if baseURL != "" {
Да, несмотря на то, что наше приложение не поддерижвает само по себе https, перед ним можно поставить тот же nginx для терминации трафика.

2024-02-15 05:05 UTC, merged